### ISSUE TITLE
如何打包成app发布

### ISSUE THREAD

**Issue by xianhaiGitHub** [wwenj/tripRecord#17]
这webApp怎么使用？就是怎么 发布使用，我本地个已经跑起来了

**Comment by xianhaiGitHub** [comment]
> 这webApp怎么使用？就是怎么发布使用，我本地已经跑起来了

**Comment by klren0312** [comment]
这就是个web应用 打包成app 你可以试试用cordova把它大包

**Comment by xianhaiGitHub** [comment]
> 这就是个web应用 打包成app 你可以试试用cordova把它大包

**Comment by xianhaiGitHub** [comment]
> 这就是个web应用 打包成app 你可以试试用cordova把它大包

这个web应用要不是打包成app感觉用处不大，没法用，只能用作练习？

**Comment by klren0312** [comment]
作者在[这里](https://github.com/wwenj/tripRecord/blob/master/README.md#%E8%A1%A5%E5%85%85)说了, 毕设
